# Generated by Django 5.0.4 on 2024-04-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Прогресс')),
                ('subtitle', models.TextField(verbose_name='Описание прогресса')),
                ('year', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': '4)Прогресс',
                'verbose_name_plural': '4)Прогрессы',
            },
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.AddField(
            model_name='settings',
            name='facebook',
            field=models.URLField(default=1, verbose_name='Ссылка на на фейсбок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp',
            field=models.URLField(default=1, verbose_name='Ссылка на ватсап'),
            preserve_default=False,
        ),
    ]
