# Generated by Django 5.0.4 on 2024-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_expmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('desc', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': '6)Журнал',
                'verbose_name_plural': '6)Журнал',
            },
        ),
        migrations.AlterModelOptions(
            name='expmodel',
            options={'verbose_name': '5)опыт', 'verbose_name_plural': '5)опыт'},
        ),
    ]
