# Generated by Django 5.0.4 on 2024-04-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('image_of_college', models.ImageField(upload_to='job_image/', verbose_name='Фото ')),
                ('desc', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': '7)Исследовать',
                'verbose_name_plural': '7)Исследовать',
            },
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': '7)Исследовать', 'verbose_name_plural': '7)Исследовать'},
        ),
    ]
