# Generated by Django 5.0.4 on 2024-04-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_latest_alter_research_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latest',
            options={'verbose_name': '8)Последние блоги', 'verbose_name_plural': '8)Последние блоги'},
        ),
    ]
